import type { Metadata } from "next";
import SignIn from "../_components/sign-in";

export const metadata: Metadata = {
  title: "Sign In",
  // description: "Generated by create next app",
};

const SignInPage = () => {
  return (
    <div className="min-h-screen w-screen flex items-center justify-center">
      <SignIn />
    </div>
  );
};

export default SignInPage;
