import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/context/theme-provider'
import { Toaster } from 'sonner'
import { FontProvider } from '@/context/font-provider'
import { DirectionProvider } from '@/context/direction-provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: {
    default: process.env.NEXT_PUBLIC_APP_NAME || 'NextDash',
    template: `%s | ${process.env.NEXT_PUBLIC_APP_NAME || 'NextDash'}`,
  },
  // description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute='class' enableSystem disableTransitionOnChange>
          <FontProvider>
            <DirectionProvider>
              <Toaster richColors />
              {children}
            </DirectionProvider>
          </FontProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
